# IMPORT QT CORE
# ///////////////////////////////////////////////////////////////
from qt_core import *

class Ui_MainPages(object):
    def setupUi(self, MainPages):
        if not MainPages.objectName():
            MainPages.setObjectName(u"MainPages")
        MainPages.resize(1052, 825)
        self.main_pages_layout = QVBoxLayout(MainPages)
        self.main_pages_layout.setSpacing(0)
        self.main_pages_layout.setObjectName(u"main_pages_layout")
        self.main_pages_layout.setContentsMargins(5, 5, 5, 5)
        self.pages = QStackedWidget(MainPages)
        self.pages.setObjectName(u"pages")
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        font = QFont()
        font.setPointSize(14)
        self.page_1.setFont(font)
        self.page_1.setStyleSheet(u"font-size: 14pt")
        self.page_1_layout = QVBoxLayout(self.page_1)
        self.page_1_layout.setSpacing(5)
        self.page_1_layout.setObjectName(u"page_1_layout")
        self.page_1_layout.setContentsMargins(5, 5, 5, 5)
        self.p1_frame = QFrame(self.page_1)
        self.p1_frame.setObjectName(u"p1_frame")
        self.p1_frame.setMaximumSize(QSize(16777215, 500))
        self.p1_frame.setLayoutDirection(Qt.LeftToRight)
        self.p1_frame.setFrameShape(QFrame.NoFrame)
        self.p1_frame.setFrameShadow(QFrame.Raised)
        self.p1_layout = QVBoxLayout(self.p1_frame)
        self.p1_layout.setSpacing(0)
        self.p1_layout.setObjectName(u"p1_layout")
        self.p1_layout.setContentsMargins(0, 0, 0, 0)
        self.p1_svg_logo_frame = QFrame(self.p1_frame)
        self.p1_svg_logo_frame.setObjectName(u"p1_svg_logo_frame")
        self.p1_svg_logo_frame.setMinimumSize(QSize(400, 0))
        self.p1_svg_logo_frame.setMaximumSize(QSize(16777215, 16777215))
        self.p1_svg_logo_frame.setFrameShape(QFrame.NoFrame)
        self.p1_svg_logo_frame.setFrameShadow(QFrame.Raised)
        self.p1_svg_logo_layout = QVBoxLayout(self.p1_svg_logo_frame)
        self.p1_svg_logo_layout.setSpacing(0)
        self.p1_svg_logo_layout.setObjectName(u"p1_svg_logo_layout")
        self.p1_svg_logo_layout.setContentsMargins(0, 0, 0, 0)

        self.p1_layout.addWidget(self.p1_svg_logo_frame)

        self.p1_label_welcome_frame = QFrame(self.p1_frame)
        self.p1_label_welcome_frame.setObjectName(u"p1_label_welcome_frame")
        self.p1_label_welcome_frame.setMinimumSize(QSize(0, 0))
        self.p1_label_welcome_frame.setMaximumSize(QSize(16777215, 16777215))
        self.p1_label_welcome_frame.setFrameShape(QFrame.NoFrame)
        self.p1_label_welcome_frame.setFrameShadow(QFrame.Raised)
        self.p1_label_welcome_layout = QVBoxLayout(self.p1_label_welcome_frame)
        self.p1_label_welcome_layout.setSpacing(0)
        self.p1_label_welcome_layout.setObjectName(u"p1_label_welcome_layout")
        self.p1_label_welcome_layout.setContentsMargins(0, 0, 0, 0)

        self.p1_layout.addWidget(self.p1_label_welcome_frame)

        self.p1_btn_start_conn_frame = QFrame(self.p1_frame)
        self.p1_btn_start_conn_frame.setObjectName(u"p1_btn_start_conn_frame")
        self.p1_btn_start_conn_frame.setMaximumSize(QSize(16777215, 16777215))
        self.p1_btn_start_conn_frame.setFrameShape(QFrame.NoFrame)
        self.p1_btn_start_conn_frame.setFrameShadow(QFrame.Raised)
        self.p1_btn_start_conn_layout = QHBoxLayout(self.p1_btn_start_conn_frame)
        self.p1_btn_start_conn_layout.setSpacing(0)
        self.p1_btn_start_conn_layout.setObjectName(u"p1_btn_start_conn_layout")
        self.p1_btn_start_conn_layout.setContentsMargins(0, 0, 0, 0)

        self.p1_layout.addWidget(self.p1_btn_start_conn_frame)


        self.page_1_layout.addWidget(self.p1_frame, 0, Qt.AlignHCenter)

        self.pages.addWidget(self.page_1)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setFont(font)
        self.page_2.setStyleSheet(u"font-size: 14pt")
        self.page_2_layout = QVBoxLayout(self.page_2)
        self.page_2_layout.setSpacing(0)
        self.page_2_layout.setObjectName(u"page_2_layout")
        self.page_2_layout.setContentsMargins(0, 0, 0, 0)
        self.p2_frame = QFrame(self.page_2)
        self.p2_frame.setObjectName(u"p2_frame")
        self.p2_frame.setMinimumSize(QSize(0, 0))
        self.p2_frame.setMaximumSize(QSize(16777215, 500))
        self.p2_frame.setLayoutDirection(Qt.LeftToRight)
        self.p2_frame.setFrameShape(QFrame.NoFrame)
        self.p2_frame.setFrameShadow(QFrame.Raised)
        self.p2_layout = QVBoxLayout(self.p2_frame)
        self.p2_layout.setSpacing(0)
        self.p2_layout.setObjectName(u"p2_layout")
        self.p2_layout.setContentsMargins(0, 0, 0, 0)
        self.p2_svg_astro_frame = QFrame(self.p2_frame)
        self.p2_svg_astro_frame.setObjectName(u"p2_svg_astro_frame")
        self.p2_svg_astro_frame.setMinimumSize(QSize(400, 152))
        self.p2_svg_astro_frame.setMaximumSize(QSize(400, 152))
        self.p2_svg_astro_frame.setFrameShape(QFrame.NoFrame)
        self.p2_svg_astro_frame.setFrameShadow(QFrame.Raised)
        self.p2_svg_astro_layout = QVBoxLayout(self.p2_svg_astro_frame)
        self.p2_svg_astro_layout.setSpacing(0)
        self.p2_svg_astro_layout.setObjectName(u"p2_svg_astro_layout")
        self.p2_svg_astro_layout.setContentsMargins(0, 0, 0, 0)

        self.p2_layout.addWidget(self.p2_svg_astro_frame)

        self.p2_label_conn_status_frame = QFrame(self.p2_frame)
        self.p2_label_conn_status_frame.setObjectName(u"p2_label_conn_status_frame")
        self.p2_label_conn_status_frame.setMaximumSize(QSize(16777215, 100))
        self.p2_label_conn_status_frame.setFrameShape(QFrame.NoFrame)
        self.p2_label_conn_status_frame.setFrameShadow(QFrame.Raised)
        self.p2_label_conn_status_layout = QVBoxLayout(self.p2_label_conn_status_frame)
        self.p2_label_conn_status_layout.setSpacing(0)
        self.p2_label_conn_status_layout.setObjectName(u"p2_label_conn_status_layout")
        self.p2_label_conn_status_layout.setContentsMargins(0, 0, 0, 0)

        self.p2_layout.addWidget(self.p2_label_conn_status_frame)

        self.p2_toggle_conn_frame = QFrame(self.p2_frame)
        self.p2_toggle_conn_frame.setObjectName(u"p2_toggle_conn_frame")
        self.p2_toggle_conn_frame.setMinimumSize(QSize(0, 0))
        self.p2_toggle_conn_frame.setMaximumSize(QSize(16777215, 100))
        self.p2_toggle_conn_frame.setFrameShape(QFrame.NoFrame)
        self.p2_toggle_conn_frame.setFrameShadow(QFrame.Raised)
        self.p2_toggle_conn_layout = QVBoxLayout(self.p2_toggle_conn_frame)
        self.p2_toggle_conn_layout.setSpacing(0)
        self.p2_toggle_conn_layout.setObjectName(u"p2_toggle_conn_layout")
        self.p2_toggle_conn_layout.setContentsMargins(0, 0, 0, 0)

        self.p2_layout.addWidget(self.p2_toggle_conn_frame)


        self.page_2_layout.addWidget(self.p2_frame, 0, Qt.AlignHCenter)

        self.pages.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.page_3.setStyleSheet(u"")
        self.page_3_layout = QVBoxLayout(self.page_3)
        self.page_3_layout.setSpacing(0)
        self.page_3_layout.setObjectName(u"page_3_layout")
        self.page_3_layout.setContentsMargins(0, 0, 0, 0)
        self.p3_scroll_area = QScrollArea(self.page_3)
        self.p3_scroll_area.setObjectName(u"p3_scroll_area")
        self.p3_scroll_area.setStyleSheet(u"background: transparent;")
        self.p3_scroll_area.setFrameShape(QFrame.NoFrame)
        self.p3_scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.p3_scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.p3_scroll_area.setWidgetResizable(True)
        self.p3_contents = QWidget()
        self.p3_contents.setObjectName(u"p3_contents")
        self.p3_contents.setGeometry(QRect(0, 0, 100, 84))
        self.p3_contents.setStyleSheet(u"background: transparent;")
        self.p3_contents_layout = QVBoxLayout(self.p3_contents)
        self.p3_contents_layout.setSpacing(15)
        self.p3_contents_layout.setObjectName(u"p3_contents_layout")
        self.p3_contents_layout.setContentsMargins(0, -1, 0, 0)
        self.p3_label_capture_frame = QFrame(self.p3_contents)
        self.p3_label_capture_frame.setObjectName(u"p3_label_capture_frame")
        self.p3_label_capture_frame.setFrameShape(QFrame.NoFrame)
        self.p3_label_capture_frame.setFrameShadow(QFrame.Raised)
        self.p3_label_capture_layout = QVBoxLayout(self.p3_label_capture_frame)
        self.p3_label_capture_layout.setSpacing(0)
        self.p3_label_capture_layout.setObjectName(u"p3_label_capture_layout")
        self.p3_label_capture_layout.setContentsMargins(0, 0, 0, 0)

        self.p3_contents_layout.addWidget(self.p3_label_capture_frame)

        self.p3_label_time_frame = QFrame(self.p3_contents)
        self.p3_label_time_frame.setObjectName(u"p3_label_time_frame")
        self.p3_label_time_frame.setFrameShape(QFrame.NoFrame)
        self.p3_label_time_frame.setFrameShadow(QFrame.Raised)
        self.p3_label_time_layout = QVBoxLayout(self.p3_label_time_frame)
        self.p3_label_time_layout.setSpacing(0)
        self.p3_label_time_layout.setObjectName(u"p3_label_time_layout")
        self.p3_label_time_layout.setContentsMargins(0, 0, 0, 0)

        self.p3_contents_layout.addWidget(self.p3_label_time_frame)

        self.p3_slider_time_frame = QFrame(self.p3_contents)
        self.p3_slider_time_frame.setObjectName(u"p3_slider_time_frame")
        self.p3_slider_time_frame.setFrameShape(QFrame.NoFrame)
        self.p3_slider_time_frame.setFrameShadow(QFrame.Raised)
        self.p3_slider_time_layout = QVBoxLayout(self.p3_slider_time_frame)
        self.p3_slider_time_layout.setSpacing(0)
        self.p3_slider_time_layout.setObjectName(u"p3_slider_time_layout")
        self.p3_slider_time_layout.setContentsMargins(0, 0, 0, 0)

        self.p3_contents_layout.addWidget(self.p3_slider_time_frame)

        self.p3_btn_capture_frame = QFrame(self.p3_contents)
        self.p3_btn_capture_frame.setObjectName(u"p3_btn_capture_frame")
        self.p3_btn_capture_frame.setFrameShape(QFrame.NoFrame)
        self.p3_btn_capture_frame.setFrameShadow(QFrame.Raised)
        self.p3_btn_capture_layout = QVBoxLayout(self.p3_btn_capture_frame)
        self.p3_btn_capture_layout.setSpacing(0)
        self.p3_btn_capture_layout.setObjectName(u"p3_btn_capture_layout")
        self.p3_btn_capture_layout.setContentsMargins(9, 0, 0, 0)

        self.p3_contents_layout.addWidget(self.p3_btn_capture_frame)

        self.p3_table_keyframes_frame = QFrame(self.p3_contents)
        self.p3_table_keyframes_frame.setObjectName(u"p3_table_keyframes_frame")
        self.p3_table_keyframes_frame.setEnabled(True)
        self.p3_table_keyframes_frame.setFrameShape(QFrame.NoFrame)
        self.p3_table_keyframes_frame.setFrameShadow(QFrame.Raised)
        self.p3_table_keyframes_layout = QHBoxLayout(self.p3_table_keyframes_frame)
        self.p3_table_keyframes_layout.setSpacing(0)
        self.p3_table_keyframes_layout.setObjectName(u"p3_table_keyframes_layout")
        self.p3_table_keyframes_layout.setContentsMargins(0, 0, 0, 0)

        self.p3_contents_layout.addWidget(self.p3_table_keyframes_frame)

        self.p3_btn_upload_frame = QFrame(self.p3_contents)
        self.p3_btn_upload_frame.setObjectName(u"p3_btn_upload_frame")
        self.p3_btn_upload_frame.setFrameShape(QFrame.NoFrame)
        self.p3_btn_upload_frame.setFrameShadow(QFrame.Raised)
        self.p3_btn_upload_layout = QVBoxLayout(self.p3_btn_upload_frame)
        self.p3_btn_upload_layout.setSpacing(0)
        self.p3_btn_upload_layout.setObjectName(u"p3_btn_upload_layout")
        self.p3_btn_upload_layout.setContentsMargins(0, 0, 0, 0)

        self.p3_contents_layout.addWidget(self.p3_btn_upload_frame)

        self.p3_scroll_area.setWidget(self.p3_contents)

        self.page_3_layout.addWidget(self.p3_scroll_area)

        self.pages.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.page_4_layout = QVBoxLayout(self.page_4)
        self.page_4_layout.setSpacing(0)
        self.page_4_layout.setObjectName(u"page_4_layout")
        self.page_4_layout.setContentsMargins(0, 0, 0, 0)
        self.p4_scroll_area = QScrollArea(self.page_4)
        self.p4_scroll_area.setObjectName(u"p4_scroll_area")
        self.p4_scroll_area.setStyleSheet(u"background: transparent;")
        self.p4_scroll_area.setFrameShape(QFrame.NoFrame)
        self.p4_scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.p4_scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.p4_scroll_area.setWidgetResizable(True)
        self.p4_contents = QWidget()
        self.p4_contents.setObjectName(u"p4_contents")
        self.p4_contents.setGeometry(QRect(0, 0, 1042, 815))
        self.p4_contents.setStyleSheet(u"background: transparent;")
        self.p4_contents_layout = QVBoxLayout(self.p4_contents)
        self.p4_contents_layout.setSpacing(15)
        self.p4_contents_layout.setObjectName(u"p4_contents_layout")
        self.p4_contents_layout.setContentsMargins(5, 5, 5, 5)
        self.p4_frame = QFrame(self.p4_contents)
        self.p4_frame.setObjectName(u"p4_frame")
        self.p4_frame.setFrameShape(QFrame.NoFrame)
        self.p4_frame.setFrameShadow(QFrame.Raised)
        self.p4_layout = QVBoxLayout(self.p4_frame)
        self.p4_layout.setObjectName(u"p4_layout")
        self.p4_layout.setContentsMargins(0, 0, 0, -1)
        self.p4_top_frame = QFrame(self.p4_frame)
        self.p4_top_frame.setObjectName(u"p4_top_frame")
        self.p4_top_frame.setFrameShape(QFrame.NoFrame)
        self.p4_top_frame.setFrameShadow(QFrame.Raised)
        self.p4_top_layout = QHBoxLayout(self.p4_top_frame)
        self.p4_top_layout.setSpacing(0)
        self.p4_top_layout.setObjectName(u"p4_top_layout")
        self.p4_top_layout.setContentsMargins(0, 0, 0, 0)
        self.p4_top_left_frame = QFrame(self.p4_top_frame)
        self.p4_top_left_frame.setObjectName(u"p4_top_left_frame")
        self.p4_top_left_frame.setFrameShape(QFrame.NoFrame)
        self.p4_top_left_frame.setFrameShadow(QFrame.Raised)
        self.p4_top_left_layout = QHBoxLayout(self.p4_top_left_frame)
        self.p4_top_left_layout.setSpacing(0)
        self.p4_top_left_layout.setObjectName(u"p4_top_left_layout")
        self.p4_top_left_layout.setContentsMargins(0, 0, 0, 0)
        self.p4_top_left_left_frame = QFrame(self.p4_top_left_frame)
        self.p4_top_left_left_frame.setObjectName(u"p4_top_left_left_frame")
        self.p4_top_left_left_frame.setMaximumSize(QSize(16777215, 16777215))
        self.p4_top_left_left_frame.setFrameShape(QFrame.NoFrame)
        self.p4_top_left_left_frame.setFrameShadow(QFrame.Raised)
        self.p4_top_left_left_layout = QVBoxLayout(self.p4_top_left_left_frame)
        self.p4_top_left_left_layout.setSpacing(20)
        self.p4_top_left_left_layout.setObjectName(u"p4_top_left_left_layout")
        self.p4_top_left_left_layout.setContentsMargins(0, 0, 50, 0)
        self.p4_top_left_left_top_frame = QFrame(self.p4_top_left_left_frame)
        self.p4_top_left_left_top_frame.setObjectName(u"p4_top_left_left_top_frame")
        self.p4_top_left_left_top_frame.setFrameShape(QFrame.NoFrame)
        self.p4_top_left_left_top_frame.setFrameShadow(QFrame.Raised)
        self.p4_top_left_left_top_layout = QVBoxLayout(self.p4_top_left_left_top_frame)
        self.p4_top_left_left_top_layout.setSpacing(10)
        self.p4_top_left_left_top_layout.setObjectName(u"p4_top_left_left_top_layout")
        self.p4_top_left_left_top_layout.setContentsMargins(0, 0, 0, 0)
        self.p4_label_pos_graph_frame = QFrame(self.p4_top_left_left_top_frame)
        self.p4_label_pos_graph_frame.setObjectName(u"p4_label_pos_graph_frame")
        self.p4_label_pos_graph_frame.setFrameShape(QFrame.NoFrame)
        self.p4_label_pos_graph_frame.setFrameShadow(QFrame.Raised)
        self.p4_label_pos_graph_layout = QHBoxLayout(self.p4_label_pos_graph_frame)
        self.p4_label_pos_graph_layout.setSpacing(0)
        self.p4_label_pos_graph_layout.setObjectName(u"p4_label_pos_graph_layout")
        self.p4_label_pos_graph_layout.setContentsMargins(0, 0, 0, 0)

        self.p4_top_left_left_top_layout.addWidget(self.p4_label_pos_graph_frame, 0, Qt.AlignHCenter)

        self.p4_btns_pos_graph_frame = QFrame(self.p4_top_left_left_top_frame)
        self.p4_btns_pos_graph_frame.setObjectName(u"p4_btns_pos_graph_frame")
        self.p4_btns_pos_graph_frame.setFrameShape(QFrame.NoFrame)
        self.p4_btns_pos_graph_frame.setFrameShadow(QFrame.Raised)
        self.p4_btns_pos_graph_layout = QHBoxLayout(self.p4_btns_pos_graph_frame)
        self.p4_btns_pos_graph_layout.setSpacing(10)
        self.p4_btns_pos_graph_layout.setObjectName(u"p4_btns_pos_graph_layout")
        self.p4_btns_pos_graph_layout.setContentsMargins(0, 0, 0, 0)

        self.p4_top_left_left_top_layout.addWidget(self.p4_btns_pos_graph_frame, 0, Qt.AlignHCenter)


        self.p4_top_left_left_layout.addWidget(self.p4_top_left_left_top_frame)

        self.p4_top_left_left_middle_frame = QFrame(self.p4_top_left_left_frame)
        self.p4_top_left_left_middle_frame.setObjectName(u"p4_top_left_left_middle_frame")
        self.p4_top_left_left_middle_frame.setFrameShape(QFrame.NoFrame)
        self.p4_top_left_left_middle_frame.setFrameShadow(QFrame.Raised)
        self.p4_top_left_left_middle_layout = QVBoxLayout(self.p4_top_left_left_middle_frame)
        self.p4_top_left_left_middle_layout.setSpacing(10)
        self.p4_top_left_left_middle_layout.setObjectName(u"p4_top_left_left_middle_layout")
        self.p4_top_left_left_middle_layout.setContentsMargins(0, 0, 0, 0)
        self.p4_label_vel_graph_frame = QFrame(self.p4_top_left_left_middle_frame)
        self.p4_label_vel_graph_frame.setObjectName(u"p4_label_vel_graph_frame")
        self.p4_label_vel_graph_frame.setFrameShape(QFrame.NoFrame)
        self.p4_label_vel_graph_frame.setFrameShadow(QFrame.Raised)
        self.p4_label_vel_graph_layout = QHBoxLayout(self.p4_label_vel_graph_frame)
        self.p4_label_vel_graph_layout.setSpacing(0)
        self.p4_label_vel_graph_layout.setObjectName(u"p4_label_vel_graph_layout")
        self.p4_label_vel_graph_layout.setContentsMargins(0, 0, 0, 0)

        self.p4_top_left_left_middle_layout.addWidget(self.p4_label_vel_graph_frame, 0, Qt.AlignHCenter)

        self.p4_btns_vel_graph_frame = QFrame(self.p4_top_left_left_middle_frame)
        self.p4_btns_vel_graph_frame.setObjectName(u"p4_btns_vel_graph_frame")
        self.p4_btns_vel_graph_frame.setFrameShape(QFrame.NoFrame)
        self.p4_btns_vel_graph_frame.setFrameShadow(QFrame.Raised)
        self.p4_btns_vel_graph_layout = QHBoxLayout(self.p4_btns_vel_graph_frame)
        self.p4_btns_vel_graph_layout.setSpacing(10)
        self.p4_btns_vel_graph_layout.setObjectName(u"p4_btns_vel_graph_layout")
        self.p4_btns_vel_graph_layout.setContentsMargins(0, 0, 0, 0)

        self.p4_top_left_left_middle_layout.addWidget(self.p4_btns_vel_graph_frame, 0, Qt.AlignHCenter)


        self.p4_top_left_left_layout.addWidget(self.p4_top_left_left_middle_frame)

        self.p4_top_left_left_bottom_frame = QFrame(self.p4_top_left_left_frame)
        self.p4_top_left_left_bottom_frame.setObjectName(u"p4_top_left_left_bottom_frame")
        self.p4_top_left_left_bottom_frame.setFrameShape(QFrame.NoFrame)
        self.p4_top_left_left_bottom_frame.setFrameShadow(QFrame.Raised)
        self.p4_top_left_left_bottom_layout = QVBoxLayout(self.p4_top_left_left_bottom_frame)
        self.p4_top_left_left_bottom_layout.setSpacing(10)
        self.p4_top_left_left_bottom_layout.setObjectName(u"p4_top_left_left_bottom_layout")
        self.p4_top_left_left_bottom_layout.setContentsMargins(0, 0, 0, 0)
        self.p4_label_accel_graph_frame = QFrame(self.p4_top_left_left_bottom_frame)
        self.p4_label_accel_graph_frame.setObjectName(u"p4_label_accel_graph_frame")
        self.p4_label_accel_graph_frame.setFrameShape(QFrame.NoFrame)
        self.p4_label_accel_graph_frame.setFrameShadow(QFrame.Raised)
        self.p4_label_accel_graph_layout = QHBoxLayout(self.p4_label_accel_graph_frame)
        self.p4_label_accel_graph_layout.setSpacing(0)
        self.p4_label_accel_graph_layout.setObjectName(u"p4_label_accel_graph_layout")
        self.p4_label_accel_graph_layout.setContentsMargins(0, 0, 0, 0)

        self.p4_top_left_left_bottom_layout.addWidget(self.p4_label_accel_graph_frame, 0, Qt.AlignHCenter)

        self.p4_btns_accel_graph_frame = QFrame(self.p4_top_left_left_bottom_frame)
        self.p4_btns_accel_graph_frame.setObjectName(u"p4_btns_accel_graph_frame")
        self.p4_btns_accel_graph_frame.setFrameShape(QFrame.NoFrame)
        self.p4_btns_accel_graph_frame.setFrameShadow(QFrame.Raised)
        self.p4_btns_accel_graph_layout = QHBoxLayout(self.p4_btns_accel_graph_frame)
        self.p4_btns_accel_graph_layout.setSpacing(10)
        self.p4_btns_accel_graph_layout.setObjectName(u"p4_btns_accel_graph_layout")
        self.p4_btns_accel_graph_layout.setContentsMargins(0, 0, 0, 0)

        self.p4_top_left_left_bottom_layout.addWidget(self.p4_btns_accel_graph_frame, 0, Qt.AlignHCenter)


        self.p4_top_left_left_layout.addWidget(self.p4_top_left_left_bottom_frame)


        self.p4_top_left_layout.addWidget(self.p4_top_left_left_frame, 0, Qt.AlignVCenter)

        self.p4_top_left_center_frame = QFrame(self.p4_top_left_frame)
        self.p4_top_left_center_frame.setObjectName(u"p4_top_left_center_frame")
        self.p4_top_left_center_frame.setFrameShape(QFrame.NoFrame)
        self.p4_top_left_center_frame.setFrameShadow(QFrame.Raised)
        self.p4_top_left_center_layout = QVBoxLayout(self.p4_top_left_center_frame)
        self.p4_top_left_center_layout.setSpacing(0)
        self.p4_top_left_center_layout.setObjectName(u"p4_top_left_center_layout")
        self.p4_top_left_center_layout.setContentsMargins(0, 0, 0, 0)
        self.p4_prev_frame = QFrame(self.p4_top_left_center_frame)
        self.p4_prev_frame.setObjectName(u"p4_prev_frame")
        self.p4_prev_frame.setFrameShape(QFrame.NoFrame)
        self.p4_prev_frame.setFrameShadow(QFrame.Raised)
        self.p4_prev_layout = QHBoxLayout(self.p4_prev_frame)
        self.p4_prev_layout.setSpacing(20)
        self.p4_prev_layout.setObjectName(u"p4_prev_layout")
        self.p4_prev_layout.setContentsMargins(0, 0, 0, 20)

        self.p4_top_left_center_layout.addWidget(self.p4_prev_frame, 0, Qt.AlignHCenter)

        self.p4_graph_frame = QFrame(self.p4_top_left_center_frame)
        self.p4_graph_frame.setObjectName(u"p4_graph_frame")
        self.p4_graph_frame.setFrameShape(QFrame.NoFrame)
        self.p4_graph_frame.setFrameShadow(QFrame.Raised)
        self.p4_graph_layout = QHBoxLayout(self.p4_graph_frame)
        self.p4_graph_layout.setSpacing(0)
        self.p4_graph_layout.setObjectName(u"p4_graph_layout")
        self.p4_graph_layout.setContentsMargins(0, 0, 0, 0)

        self.p4_top_left_center_layout.addWidget(self.p4_graph_frame)

        self.p4_btns_prev_frame = QFrame(self.p4_top_left_center_frame)
        self.p4_btns_prev_frame.setObjectName(u"p4_btns_prev_frame")
        self.p4_btns_prev_frame.setFrameShape(QFrame.NoFrame)
        self.p4_btns_prev_frame.setFrameShadow(QFrame.Raised)
        self.p4_btns_prev_layout = QHBoxLayout(self.p4_btns_prev_frame)
        self.p4_btns_prev_layout.setSpacing(20)
        self.p4_btns_prev_layout.setObjectName(u"p4_btns_prev_layout")
        self.p4_btns_prev_layout.setContentsMargins(0, 20, 0, 0)

        self.p4_top_left_center_layout.addWidget(self.p4_btns_prev_frame, 0, Qt.AlignHCenter)


        self.p4_top_left_layout.addWidget(self.p4_top_left_center_frame)

        self.p4_top_left_right_frame = QFrame(self.p4_top_left_frame)
        self.p4_top_left_right_frame.setObjectName(u"p4_top_left_right_frame")
        self.p4_top_left_right_frame.setFrameShape(QFrame.NoFrame)
        self.p4_top_left_right_frame.setFrameShadow(QFrame.Raised)
        self.p4_top_left_right_layout = QVBoxLayout(self.p4_top_left_right_frame)
        self.p4_top_left_right_layout.setSpacing(0)
        self.p4_top_left_right_layout.setObjectName(u"p4_top_left_right_layout")
        self.p4_top_left_right_layout.setContentsMargins(50, 0, 0, 0)
        self.p4_btns_2d3d_frame = QFrame(self.p4_top_left_right_frame)
        self.p4_btns_2d3d_frame.setObjectName(u"p4_btns_2d3d_frame")
        self.p4_btns_2d3d_frame.setFrameShape(QFrame.NoFrame)
        self.p4_btns_2d3d_frame.setFrameShadow(QFrame.Raised)
        self.p4_btns_2d3d_layout = QVBoxLayout(self.p4_btns_2d3d_frame)
        self.p4_btns_2d3d_layout.setSpacing(10)
        self.p4_btns_2d3d_layout.setObjectName(u"p4_btns_2d3d_layout")
        self.p4_btns_2d3d_layout.setContentsMargins(0, 0, 0, 50)

        self.p4_top_left_right_layout.addWidget(self.p4_btns_2d3d_frame, 0, Qt.AlignTop)

        self.p4_btns_pantilt_frame = QFrame(self.p4_top_left_right_frame)
        self.p4_btns_pantilt_frame.setObjectName(u"p4_btns_pantilt_frame")
        self.p4_btns_pantilt_frame.setFrameShape(QFrame.NoFrame)
        self.p4_btns_pantilt_frame.setFrameShadow(QFrame.Raised)
        self.p4_btns_pantilt_layout = QVBoxLayout(self.p4_btns_pantilt_frame)
        self.p4_btns_pantilt_layout.setSpacing(10)
        self.p4_btns_pantilt_layout.setObjectName(u"p4_btns_pantilt_layout")
        self.p4_btns_pantilt_layout.setContentsMargins(0, 0, 0, 0)

        self.p4_top_left_right_layout.addWidget(self.p4_btns_pantilt_frame, 0, Qt.AlignBottom)


        self.p4_top_left_layout.addWidget(self.p4_top_left_right_frame, 0, Qt.AlignVCenter)


        self.p4_top_layout.addWidget(self.p4_top_left_frame)

        self.p4_top_right_frame = QFrame(self.p4_top_frame)
        self.p4_top_right_frame.setObjectName(u"p4_top_right_frame")
        self.p4_top_right_frame.setFrameShape(QFrame.NoFrame)
        self.p4_top_right_frame.setFrameShadow(QFrame.Raised)
        self.p4_top_right_layout = QVBoxLayout(self.p4_top_right_frame)
        self.p4_top_right_layout.setSpacing(0)
        self.p4_top_right_layout.setObjectName(u"p4_top_right_layout")
        self.p4_top_right_layout.setContentsMargins(100, 0, 0, 0)
        self.p4_edit_frame = QFrame(self.p4_top_right_frame)
        self.p4_edit_frame.setObjectName(u"p4_edit_frame")
        self.p4_edit_frame.setFrameShape(QFrame.NoFrame)
        self.p4_edit_frame.setFrameShadow(QFrame.Raised)
        self.p4_edit_layout = QHBoxLayout(self.p4_edit_frame)
        self.p4_edit_layout.setSpacing(20)
        self.p4_edit_layout.setObjectName(u"p4_edit_layout")
        self.p4_edit_layout.setContentsMargins(0, 0, 0, 20)

        self.p4_top_right_layout.addWidget(self.p4_edit_frame, 0, Qt.AlignHCenter)

        self.p4_label_keyframe_frame = QFrame(self.p4_top_right_frame)
        self.p4_label_keyframe_frame.setObjectName(u"p4_label_keyframe_frame")
        self.p4_label_keyframe_frame.setFrameShape(QFrame.NoFrame)
        self.p4_label_keyframe_frame.setFrameShadow(QFrame.Raised)
        self.p4_label_keyframe_layout = QHBoxLayout(self.p4_label_keyframe_frame)
        self.p4_label_keyframe_layout.setSpacing(15)
        self.p4_label_keyframe_layout.setObjectName(u"p4_label_keyframe_layout")
        self.p4_label_keyframe_layout.setContentsMargins(0, 0, 0, 30)

        self.p4_top_right_layout.addWidget(self.p4_label_keyframe_frame, 0, Qt.AlignLeft)

        self.p4_settings_frame = QFrame(self.p4_top_right_frame)
        self.p4_settings_frame.setObjectName(u"p4_settings_frame")
        self.p4_settings_frame.setMaximumSize(QSize(16777215, 16777215))
        self.p4_settings_frame.setFrameShape(QFrame.NoFrame)
        self.p4_settings_frame.setFrameShadow(QFrame.Raised)
        self.p4_settings_layout = QVBoxLayout(self.p4_settings_frame)
        self.p4_settings_layout.setSpacing(0)
        self.p4_settings_layout.setObjectName(u"p4_settings_layout")
        self.p4_settings_layout.setContentsMargins(0, 0, 0, 0)
        self.p4_easein_frame = QFrame(self.p4_settings_frame)
        self.p4_easein_frame.setObjectName(u"p4_easein_frame")
        self.p4_easein_frame.setMinimumSize(QSize(0, 0))
        self.p4_easein_frame.setFrameShape(QFrame.NoFrame)
        self.p4_easein_frame.setFrameShadow(QFrame.Raised)
        self.p4_easein_layout = QHBoxLayout(self.p4_easein_frame)
        self.p4_easein_layout.setSpacing(30)
        self.p4_easein_layout.setObjectName(u"p4_easein_layout")
        self.p4_easein_layout.setContentsMargins(0, 0, 0, 0)

        self.p4_settings_layout.addWidget(self.p4_easein_frame, 0, Qt.AlignLeft|Qt.AlignVCenter)

        self.p4_easeout_frame = QFrame(self.p4_settings_frame)
        self.p4_easeout_frame.setObjectName(u"p4_easeout_frame")
        self.p4_easeout_frame.setFrameShape(QFrame.NoFrame)
        self.p4_easeout_frame.setFrameShadow(QFrame.Raised)
        self.p4_easeout_layout = QHBoxLayout(self.p4_easeout_frame)
        self.p4_easeout_layout.setSpacing(30)
        self.p4_easeout_layout.setObjectName(u"p4_easeout_layout")
        self.p4_easeout_layout.setContentsMargins(0, 30, 0, 0)

        self.p4_settings_layout.addWidget(self.p4_easeout_frame, 0, Qt.AlignLeft|Qt.AlignVCenter)

        self.p4_position_frame = QFrame(self.p4_settings_frame)
        self.p4_position_frame.setObjectName(u"p4_position_frame")
        self.p4_position_frame.setMinimumSize(QSize(700, 0))
        self.p4_position_frame.setMaximumSize(QSize(700, 16777215))
        self.p4_position_frame.setFrameShape(QFrame.NoFrame)
        self.p4_position_frame.setFrameShadow(QFrame.Raised)
        self.p4_position_layout = QHBoxLayout(self.p4_position_frame)
        self.p4_position_layout.setSpacing(30)
        self.p4_position_layout.setObjectName(u"p4_position_layout")
        self.p4_position_layout.setContentsMargins(0, 30, 0, 0)
        self.p4_label_position_frame = QFrame(self.p4_position_frame)
        self.p4_label_position_frame.setObjectName(u"p4_label_position_frame")
        self.p4_label_position_frame.setMinimumSize(QSize(0, 20))
        self.p4_label_position_frame.setFrameShape(QFrame.NoFrame)
        self.p4_label_position_frame.setFrameShadow(QFrame.Raised)
        self.p4_label_position_layout = QHBoxLayout(self.p4_label_position_frame)
        self.p4_label_position_layout.setSpacing(0)
        self.p4_label_position_layout.setObjectName(u"p4_label_position_layout")
        self.p4_label_position_layout.setContentsMargins(0, 0, 0, 0)

        self.p4_position_layout.addWidget(self.p4_label_position_frame)

        self.p4_sliders_position_frame = QFrame(self.p4_position_frame)
        self.p4_sliders_position_frame.setObjectName(u"p4_sliders_position_frame")
        self.p4_sliders_position_frame.setMinimumSize(QSize(0, 0))
        self.p4_sliders_position_frame.setMaximumSize(QSize(16777215, 16777215))
        self.p4_sliders_position_frame.setFrameShape(QFrame.NoFrame)
        self.p4_sliders_position_frame.setFrameShadow(QFrame.Raised)
        self.p4_sliders_position_layout = QVBoxLayout(self.p4_sliders_position_frame)
        self.p4_sliders_position_layout.setSpacing(10)
        self.p4_sliders_position_layout.setObjectName(u"p4_sliders_position_layout")
        self.p4_sliders_position_layout.setContentsMargins(0, 0, 0, 0)
        self.p4_slider_pos_n_frame = QFrame(self.p4_sliders_position_frame)
        self.p4_slider_pos_n_frame.setObjectName(u"p4_slider_pos_n_frame")
        self.p4_slider_pos_n_frame.setMaximumSize(QSize(16777215, 16777215))
        self.p4_slider_pos_n_frame.setFrameShape(QFrame.NoFrame)
        self.p4_slider_pos_n_frame.setFrameShadow(QFrame.Raised)
        self.p4_slider_pos_n_layout = QHBoxLayout(self.p4_slider_pos_n_frame)
        self.p4_slider_pos_n_layout.setSpacing(10)
        self.p4_slider_pos_n_layout.setObjectName(u"p4_slider_pos_n_layout")
        self.p4_slider_pos_n_layout.setContentsMargins(0, 0, 0, 0)

        self.p4_sliders_position_layout.addWidget(self.p4_slider_pos_n_frame, 0, Qt.AlignLeft|Qt.AlignVCenter)

        self.p4_slider_pos_e_frame = QFrame(self.p4_sliders_position_frame)
        self.p4_slider_pos_e_frame.setObjectName(u"p4_slider_pos_e_frame")
        self.p4_slider_pos_e_frame.setMaximumSize(QSize(16777215, 16777215))
        self.p4_slider_pos_e_frame.setFrameShape(QFrame.NoFrame)
        self.p4_slider_pos_e_frame.setFrameShadow(QFrame.Raised)
        self.p4_slider_pos_e_layout = QHBoxLayout(self.p4_slider_pos_e_frame)
        self.p4_slider_pos_e_layout.setSpacing(10)
        self.p4_slider_pos_e_layout.setObjectName(u"p4_slider_pos_e_layout")
        self.p4_slider_pos_e_layout.setContentsMargins(0, 0, 0, 0)

        self.p4_sliders_position_layout.addWidget(self.p4_slider_pos_e_frame, 0, Qt.AlignLeft|Qt.AlignVCenter)

        self.p4_slider_pos_relalt_frame = QFrame(self.p4_sliders_position_frame)
        self.p4_slider_pos_relalt_frame.setObjectName(u"p4_slider_pos_relalt_frame")
        self.p4_slider_pos_relalt_frame.setFrameShape(QFrame.NoFrame)
        self.p4_slider_pos_relalt_frame.setFrameShadow(QFrame.Raised)
        self.p4_slider_pos_relalt_layout = QHBoxLayout(self.p4_slider_pos_relalt_frame)
        self.p4_slider_pos_relalt_layout.setSpacing(10)
        self.p4_slider_pos_relalt_layout.setObjectName(u"p4_slider_pos_relalt_layout")
        self.p4_slider_pos_relalt_layout.setContentsMargins(0, 0, 0, 0)

        self.p4_sliders_position_layout.addWidget(self.p4_slider_pos_relalt_frame, 0, Qt.AlignLeft|Qt.AlignVCenter)


        self.p4_position_layout.addWidget(self.p4_sliders_position_frame, 0, Qt.AlignLeft|Qt.AlignVCenter)


        self.p4_settings_layout.addWidget(self.p4_position_frame, 0, Qt.AlignLeft|Qt.AlignVCenter)

        self.p4_orientation_frame = QFrame(self.p4_settings_frame)
        self.p4_orientation_frame.setObjectName(u"p4_orientation_frame")
        self.p4_orientation_frame.setMinimumSize(QSize(500, 0))
        self.p4_orientation_frame.setMaximumSize(QSize(500, 16777215))
        self.p4_orientation_frame.setFrameShape(QFrame.NoFrame)
        self.p4_orientation_frame.setFrameShadow(QFrame.Raised)
        self.p4_orientation_layout = QHBoxLayout(self.p4_orientation_frame)
        self.p4_orientation_layout.setSpacing(30)
        self.p4_orientation_layout.setObjectName(u"p4_orientation_layout")
        self.p4_orientation_layout.setContentsMargins(0, 30, 0, 0)

        self.p4_settings_layout.addWidget(self.p4_orientation_frame, 0, Qt.AlignLeft|Qt.AlignVCenter)

        self.p4_time_frame = QFrame(self.p4_settings_frame)
        self.p4_time_frame.setObjectName(u"p4_time_frame")
        self.p4_time_frame.setFrameShape(QFrame.NoFrame)
        self.p4_time_frame.setFrameShadow(QFrame.Raised)
        self.p4_time_layout = QHBoxLayout(self.p4_time_frame)
        self.p4_time_layout.setSpacing(30)
        self.p4_time_layout.setObjectName(u"p4_time_layout")
        self.p4_time_layout.setContentsMargins(0, 30, 0, 0)

        self.p4_settings_layout.addWidget(self.p4_time_frame, 0, Qt.AlignLeft|Qt.AlignVCenter)


        self.p4_top_right_layout.addWidget(self.p4_settings_frame)


        self.p4_top_layout.addWidget(self.p4_top_right_frame, 0, Qt.AlignTop)


        self.p4_layout.addWidget(self.p4_top_frame, 0, Qt.AlignHCenter|Qt.AlignTop)

        self.p4_bottom_frame = QFrame(self.p4_frame)
        self.p4_bottom_frame.setObjectName(u"p4_bottom_frame")
        self.p4_bottom_frame.setFrameShape(QFrame.NoFrame)
        self.p4_bottom_frame.setFrameShadow(QFrame.Raised)
        self.p4_bottom_layout = QHBoxLayout(self.p4_bottom_frame)
        self.p4_bottom_layout.setSpacing(0)
        self.p4_bottom_layout.setObjectName(u"p4_bottom_layout")
        self.p4_bottom_layout.setContentsMargins(0, 50, 0, 0)

        self.p4_layout.addWidget(self.p4_bottom_frame, 0, Qt.AlignHCenter)


        self.p4_contents_layout.addWidget(self.p4_frame, 0, Qt.AlignHCenter|Qt.AlignVCenter)

        self.p4_scroll_area.setWidget(self.p4_contents)

        self.page_4_layout.addWidget(self.p4_scroll_area)

        self.pages.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.page_5.setStyleSheet(u"QFrame {\n"
"	font-size: 16pt;\n"
"}")
        self.page_5_layout = QVBoxLayout(self.page_5)
        self.page_5_layout.setObjectName(u"page_5_layout")
        self.p5_scroll_area = QScrollArea(self.page_5)
        self.p5_scroll_area.setObjectName(u"p5_scroll_area")
        self.p5_scroll_area.setStyleSheet(u"background: transparent;")
        self.p5_scroll_area.setFrameShape(QFrame.NoFrame)
        self.p5_scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.p5_scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.p5_scroll_area.setWidgetResizable(True)
        self.p5_contents = QWidget()
        self.p5_contents.setObjectName(u"p5_contents")
        self.p5_contents.setGeometry(QRect(0, 0, 1024, 797))
        self.p5_contents.setStyleSheet(u"background: transparent;")
        self.p5_layout = QVBoxLayout(self.p5_contents)
        self.p5_layout.setSpacing(0)
        self.p5_layout.setObjectName(u"p5_layout")
        self.p5_layout.setContentsMargins(0, 0, 0, 0)
        self.p5_top_frame = QFrame(self.p5_contents)
        self.p5_top_frame.setObjectName(u"p5_top_frame")
        self.p5_top_frame.setFrameShape(QFrame.NoFrame)
        self.p5_top_frame.setFrameShadow(QFrame.Raised)
        self.p5_top_layout = QVBoxLayout(self.p5_top_frame)
        self.p5_top_layout.setSpacing(0)
        self.p5_top_layout.setObjectName(u"p5_top_layout")
        self.p5_top_layout.setContentsMargins(0, 0, 0, 0)
        self.p5_progress_frame = QFrame(self.p5_top_frame)
        self.p5_progress_frame.setObjectName(u"p5_progress_frame")
        self.p5_progress_frame.setFrameShape(QFrame.NoFrame)
        self.p5_progress_frame.setFrameShadow(QFrame.Raised)
        self.p5_progress_layout = QHBoxLayout(self.p5_progress_frame)
        self.p5_progress_layout.setSpacing(0)
        self.p5_progress_layout.setObjectName(u"p5_progress_layout")
        self.p5_progress_layout.setContentsMargins(0, 0, 0, 0)

        self.p5_top_layout.addWidget(self.p5_progress_frame)

        self.p5_label_time_rem_frame = QFrame(self.p5_top_frame)
        self.p5_label_time_rem_frame.setObjectName(u"p5_label_time_rem_frame")
        self.p5_label_time_rem_frame.setFrameShape(QFrame.NoFrame)
        self.p5_label_time_rem_frame.setFrameShadow(QFrame.Raised)
        self.p5_label_time_rem_layout = QHBoxLayout(self.p5_label_time_rem_frame)
        self.p5_label_time_rem_layout.setSpacing(0)
        self.p5_label_time_rem_layout.setObjectName(u"p5_label_time_rem_layout")
        self.p5_label_time_rem_layout.setContentsMargins(0, 0, 0, 0)

        self.p5_top_layout.addWidget(self.p5_label_time_rem_frame)

        self.p5_btns_control_frame = QFrame(self.p5_top_frame)
        self.p5_btns_control_frame.setObjectName(u"p5_btns_control_frame")
        self.p5_btns_control_frame.setFrameShape(QFrame.NoFrame)
        self.p5_btns_control_frame.setFrameShadow(QFrame.Raised)
        self.p5_btns_control_layout = QHBoxLayout(self.p5_btns_control_frame)
        self.p5_btns_control_layout.setSpacing(0)
        self.p5_btns_control_layout.setObjectName(u"p5_btns_control_layout")
        self.p5_btns_control_layout.setContentsMargins(0, 0, 0, 0)

        self.p5_top_layout.addWidget(self.p5_btns_control_frame)

        self.p5_label_monitor_frame = QFrame(self.p5_top_frame)
        self.p5_label_monitor_frame.setObjectName(u"p5_label_monitor_frame")
        self.p5_label_monitor_frame.setFrameShape(QFrame.NoFrame)
        self.p5_label_monitor_frame.setFrameShadow(QFrame.Raised)
        self.p5_label_monitor_layout = QHBoxLayout(self.p5_label_monitor_frame)
        self.p5_label_monitor_layout.setSpacing(0)
        self.p5_label_monitor_layout.setObjectName(u"p5_label_monitor_layout")
        self.p5_label_monitor_layout.setContentsMargins(0, 0, 0, 0)

        self.p5_top_layout.addWidget(self.p5_label_monitor_frame)

        self.p5_graphs_frame = QFrame(self.p5_top_frame)
        self.p5_graphs_frame.setObjectName(u"p5_graphs_frame")
        self.p5_graphs_frame.setFrameShape(QFrame.NoFrame)
        self.p5_graphs_frame.setFrameShadow(QFrame.Raised)
        self.p5_graphs_layout = QHBoxLayout(self.p5_graphs_frame)
        self.p5_graphs_layout.setSpacing(0)
        self.p5_graphs_layout.setObjectName(u"p5_graphs_layout")
        self.p5_graphs_layout.setContentsMargins(0, 0, 0, 0)

        self.p5_top_layout.addWidget(self.p5_graphs_frame)


        self.p5_layout.addWidget(self.p5_top_frame)

        self.p5_scroll_area.setWidget(self.p5_contents)

        self.page_5_layout.addWidget(self.p5_scroll_area)

        self.pages.addWidget(self.page_5)
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.page_6.setStyleSheet(u"QFrame {\n"
"	font-size: 16pt;\n"
"}")
        self.page_6_layout = QVBoxLayout(self.page_6)
        self.page_6_layout.setObjectName(u"page_6_layout")
        self.p6_scroll_area = QScrollArea(self.page_6)
        self.p6_scroll_area.setObjectName(u"p6_scroll_area")
        self.p6_scroll_area.setStyleSheet(u"background: transparent;")
        self.p6_scroll_area.setFrameShape(QFrame.NoFrame)
        self.p6_scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.p6_scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.p6_scroll_area.setWidgetResizable(True)
        self.p6_contents = QWidget()
        self.p6_contents.setObjectName(u"p6_contents")
        self.p6_contents.setGeometry(QRect(0, 0, 1024, 797))
        self.p6_contents.setStyleSheet(u"background: transparent;")
        self.p6_layout = QVBoxLayout(self.p6_contents)
        self.p6_layout.setSpacing(0)
        self.p6_layout.setObjectName(u"p6_layout")
        self.p6_layout.setContentsMargins(0, 0, 0, 0)
        self.p6_bottom_frame = QFrame(self.p6_contents)
        self.p6_bottom_frame.setObjectName(u"p6_bottom_frame")
        self.p6_bottom_frame.setFrameShape(QFrame.NoFrame)
        self.p6_bottom_frame.setFrameShadow(QFrame.Raised)
        self.p6_bottom_layout = QVBoxLayout(self.p6_bottom_frame)
        self.p6_bottom_layout.setSpacing(0)
        self.p6_bottom_layout.setObjectName(u"p6_bottom_layout")
        self.p6_bottom_layout.setContentsMargins(0, 0, 0, 0)
        self.p6_label_review_file_frame = QFrame(self.p6_bottom_frame)
        self.p6_label_review_file_frame.setObjectName(u"p6_label_review_file_frame")
        self.p6_label_review_file_frame.setFrameShape(QFrame.NoFrame)
        self.p6_label_review_file_frame.setFrameShadow(QFrame.Raised)
        self.p6_label_review_file_layout = QHBoxLayout(self.p6_label_review_file_frame)
        self.p6_label_review_file_layout.setSpacing(0)
        self.p6_label_review_file_layout.setObjectName(u"p6_label_review_file_layout")
        self.p6_label_review_file_layout.setContentsMargins(0, 0, 0, 0)

        self.p6_bottom_layout.addWidget(self.p6_label_review_file_frame)

        self.p6_graphs_frame_TODO = QFrame(self.p6_bottom_frame)
        self.p6_graphs_frame_TODO.setObjectName(u"p6_graphs_frame_TODO")
        self.p6_graphs_frame_TODO.setFrameShape(QFrame.NoFrame)
        self.p6_graphs_frame_TODO.setFrameShadow(QFrame.Raised)
        self.p6_graphs_layout_TODO = QHBoxLayout(self.p6_graphs_frame_TODO)
        self.p6_graphs_layout_TODO.setSpacing(0)
        self.p6_graphs_layout_TODO.setObjectName(u"p6_graphs_layout_TODO")
        self.p6_graphs_layout_TODO.setContentsMargins(0, 0, 0, 0)

        self.p6_bottom_layout.addWidget(self.p6_graphs_frame_TODO)

        self.p6_label_table_frame = QFrame(self.p6_bottom_frame)
        self.p6_label_table_frame.setObjectName(u"p6_label_table_frame")
        self.p6_label_table_frame.setFrameShape(QFrame.NoFrame)
        self.p6_label_table_frame.setFrameShadow(QFrame.Raised)
        self.p6_label_table_layout = QHBoxLayout(self.p6_label_table_frame)
        self.p6_label_table_layout.setSpacing(0)
        self.p6_label_table_layout.setObjectName(u"p6_label_table_layout")
        self.p6_label_table_layout.setContentsMargins(0, 0, 0, 0)

        self.p6_bottom_layout.addWidget(self.p6_label_table_frame)

        self.p6_table_frame = QFrame(self.p6_bottom_frame)
        self.p6_table_frame.setObjectName(u"p6_table_frame")
        self.p6_table_frame.setFrameShape(QFrame.NoFrame)
        self.p6_table_frame.setFrameShadow(QFrame.Raised)
        self.p6_table_layout = QHBoxLayout(self.p6_table_frame)
        self.p6_table_layout.setSpacing(0)
        self.p6_table_layout.setObjectName(u"p6_table_layout")
        self.p6_table_layout.setContentsMargins(0, 0, 0, 0)

        self.p6_bottom_layout.addWidget(self.p6_table_frame)


        self.p6_layout.addWidget(self.p6_bottom_frame)

        self.p6_scroll_area.setWidget(self.p6_contents)

        self.page_6_layout.addWidget(self.p6_scroll_area)

        self.pages.addWidget(self.page_6)

        self.main_pages_layout.addWidget(self.pages)


        self.retranslateUi(MainPages)

        self.pages.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(MainPages)
    # setupUi

    def retranslateUi(self, MainPages):
        MainPages.setWindowTitle(QCoreApplication.translate("MainPages", u"Form", None))
    # retranslateUi

